### ISSUE TITLE
release to CPAN?

### ISSUE THREAD

**Issue by mr-c** [bioperl/Bio-DB-SwissProt#2]
Hello,

We'd like to package this for Debian so we can run more of the Bio::Perl tests

Thank you for your maintenance work!

**Comment by carandraug** [comment]
If someone is interested in taking in maintenance of the Bio-Variation distribution, leave a comment. It doesn't look like any of the current maintainers of BioPerl has the time to do so.

**Comment by cjfields** [comment]
@mr-c @carandraug I think we can push out a quick release to CPAN, will post back if this works. The more problematic one will be `Bio::DB::RefSeq`.

**Comment by cjfields** [comment]
The distribution successfully indexed and is now on CPAN:

https://metacpan.org/pod/Bio::DB::SwissProt

**Comment by mr-c** [comment]
@cjfields Thanks! I've made the package and requested it to be sponsored for addition to Debian
